name: reviewdog
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint-github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          stylelint_config: 'stylelint-config-recommended'
          stylelint_ignore: '/testdata-subproject/'
      - name: stylelint-github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          stylelint_ignore: '/testdata-subproject/'
      - name: stylelint-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_ignore: '/testdata-subproject/'
      - name: stylelint-github-pr-check-subproject
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          stylelint_config: 'stylelint-config-recommended'
          workdir: ./testdata-subproject
      - name: stylelint-github-check-subproject
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          workdir: ./testdata-subproject
      - name: stylelint-github-pr-review-subproject
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ./testdata-subproject
